# Gems for basic scripts.  Needed for now, but soon to add self-installer to scripts
source 'https://rubygems.org'

gem 'activesupport'
gem 'chef', '>=11.8.2'
gem 'compass'
gem 'deep_merge'
gem 'diff-lcs'
gem 'fog'
gem 'git'
gem 'ini'
gem 'jenkins_api_client', '>= 1.0.0'
gem 'json'
gem 'json-schema'
gem 'logger'
gem 'metric_fu'
gem 'minitest'
gem 'mixlib-cli'
gem 'mixlib-config'
gem 'mocha'
gem 'net-ssh'
gem 'net-ssh-multi'
gem 'nokogiri'
gem 'open4'
gem 'rubocop'
gem 'simplecov'
gem 'sys-proctable'
gem 'unf'
gem 'xml-simple'
gem 'zip'
