# Gems for Graham Trummell's scripts
source 'https://rubygems.org'

gem 'activesupport'
gem 'chef', '>=11.8.2'
gem 'deep_merge'
gem 'diff-lcs'
gem 'fog'
gem 'git'
gem 'gitflow'
gem 'ini'
gem 'jenkins_api_client', '>= 1.0.0.beta.5'
gem 'json-schema'
gem 'logger'
gem 'metric_fu'
gem 'minitest'
gem 'mixlib-cli'
gem 'mixlib-config'
gem 'mocha'
gem 'net-ssh'
gem 'net-ssh-multi'
gem 'nokogiri', '= 1.6.2.1'
gem 'open4'
gem 'rubocop'
gem 'simplecov'
gem 'unf'
gem 'xml-simple'
gem 'zip'
